
# +------------------------------------------------------+
# |               DREFilter Configuration                |
# +------------------------------------------------------+

# Note:    You can change any of these options while the server is running.
#          To load your changes on the running server, use the /drefilter reload command.

# The damage reduction multiplier (damage = damage*multiplier)
reducedDamageMultiplier: 0.5
# Every world listed here will be affected by the filter.
affectedWorlds:
  - "Saragandes"

# Every item with a material contained in this list won't deal any damage.
# To disable a specific tool type, just write the name of it.
noDamageItems:
  - "AXE"
  - "PICKAXE"
  - "SHOVEL"
  - "HOE"

# If an item has one of the following lore lines, the damage filter won't affect them.
ignoreDamageFilterLore:
  - "&7Streitaxt"
  - "&7Holzfälleraxt"

# This lore line will be added to every item dealing 0 damage.
noDamageItemLore: "&5Werkzeug"

# If true: all villager interactions will get canceled.
# If false: default interactions
villagerDisabled: false

# Enchantment list
# enabled:  Write down the maximum level of the enchantment that is allowed.
#           Higher level than allowed will get downgraded.
#           If the number is 0 or below: the enchantment will be removed.

# disabled: Enchantments that aren't listed won't be affected by the filter.
#           Remove the '#' in front of the enchantment to enable the filter on it.
#           Enabled enchantments with a null value won't be affected either.
enchantments:
  DAMAGE_ALL: 2
#  DAMAGE_ARTHROPODS:
#  DAMAGE_UNDEAD:
  ARROW_DAMAGE: 2
#  ARROW_INFINITE:
  ARROW_KNOCKBACK: 1
  ARROW_FIRE: 0
  PROTECTION_ENVIRONMENTAL: 1
  PROTECTION_FIRE: 0
  PROTECTION_PROJECTILE: 0
  PROTECTION_EXPLOSIONS: 0
#  PROTECTION_FALL:
  THORNS: 0
  SWEEPING_EDGE: 0
#  FIRE_ASPECT:
#  KNOCKBACK:
#  LOOT_BONUS_MOBS:
#  LOOT_BONUS_BLOCKS:
#  DIG_SPEED:
#  SILK_TOUCH:
#  DURABILITY:
#  MENDING:
#  FROST_WALKER:
#  WATER_WORKER:
#  DEPTH_STRIDER:
#  OXYGEN:
#  RIPTIDE:
#  CHANNELING:
#  VANISHING_CURSE:
#  BINDING_CURSE:
#  LUCK:
#  LURE:
#  IMPALING:
#  LOYALTY:
#  PIERCING:
#  MULTI_SHOT:
#  QUICK_CHARGE:
