name: DREFilter
version: 1.0.6
main: de.fyreum.drefilter.DREFilter
api-version: 1.13
authors: [Fyreum]
description: Filter für Verzauberungen und mehr.
website: erethon.de
commands:
  drefilter:
    description: reloads the plugin