name: DREFilter
version: 1.0.5
main: de.fyreum.drefilter.DREFilter
api-version: 1.15
authors: [Fyreum]
description: Filter für Verzauberungen und mehr.
website: erethon.de
commands:
  drefilter:
    description: reloads the plugin